translate(scaling-up): SFC
Abdelaziz18003/vuejs-docs-ar pull request #74
Opened 2023-03-10 23:08 UTC by ousszizou

2023-03-11 10:55 UTC, boussadjra reviewed
كملاحظة عامة، يجب الحفاظ على المعنى و إثرائه و عدم التقيد بالتركيب الإنجليزي.

2023-03-11 10:55 UTC, boussadjra commented on src/guide/scaling-up/sfc.md
> +يمكنك اللعب مع ملفات SFC و استكشاف كيفية تجميعها في [Vue SFC Playground](https://sfc.vuejs.org/).
أرى كلمة لعب تبدو مبتذلة نوعا 
 يمكنك تجربة المكونات أحادية الملف واستكشاف كيفية تصريفها في ...

2023-03-11 10:55 UTC, boussadjra commented on src/guide/scaling-up/sfc.md
> +بعض المستخدمين القادمين من خلفية تطوير الويب التقليدية قد يكون لديهم القلق من أن  المكونات أحادية الملف تخلط اهتمامات مختلفة في نفس المكان - والتي كان من المفترض أن تفصلها HTML / CSS / JS!
هل ترى فعلا أن كلمة الاهتمامات تفي بالمعنى، ربما من المستحسن قول نوع الشيفرات، للمزيد من التفاصيل اطلع على هذا النقاش #75

2023-03-20 08:07 UTC, boussadjra requested changes
يرجى تعديل الترجمة إن أمكن و شكرا

2023-03-20 08:14 UTC, medaminefh commented on src/guide/scaling-up/sfc.md
> +- تطبيقات الصفحة الواحدة ( SPA )
هل تم الاتفاق علي تعريب SPA ل'تطبيق أحادي الملف' ? لأني أري أن 'تطبيق الصفحة الواحدة' اكثر دقة

2023-03-20 08:24 UTC, boussadjra commented on src/guide/scaling-up/sfc.md
> +- تطبيقات الصفحة الواحدة ( SPA )
آسف أقصد تطبيق أحادي الصفحة

2023-03-22 05:16 UTC, boussadjra approved these changes
شكرا لمساهمتك

2023-03-22 05:16 UTC, merged