Translate(best-practices/performance)
Abdelaziz18003/vuejs-docs-ar pull request #82
Opened 2023-03-21 21:34 UTC by medaminefh

2023-03-23 10:07 UTC, boussadjra requested changes
شكرا على المساهمة
كملاحظة إذا كنت تستخدم مترجم آلي كمترجم google فمن الضروري إعادة صياغة الفقرة المترجمة حتى تتناسب مع المعنى أولا و أيضا مع مجموعة المصطلحات المستعملة في التوثيق.

2023-03-23 10:07 UTC, boussadjra commented on src/guide/best-practices/performance.md
> +لاحظ أن تقليل عدد قليل فقط من النسخ لن يكون له تأثير ملحوظ ، لذلك لا تقلق إذا عرض المكون عدة مرات فقط في التطبيق. أفضل سيناريو للنظر في هذا التحسين هو مرة أخرى في القوائم الكبيرة. تخيل قائمة تضم 100
تجدر الملاحظة أن حذف عدد قليل فقط من النسخ لن يكون له تأثير ملحوظ ، لذلك لا تقلق إذا صُيِّر المكون عدة مرات فقط في التطبيق. أفضل سيناريو للنظر في هذا التحسين هو مرة أخرى في القوائم الكبيرة. تخيل قائمة تضم 100 عنصر حيث يحتوي كل مكون عنصر على العديد من المكونات الأبناء. قد تؤدي إزالة أحد تجريدات المكون غير الضرورية هنا إلى تقليل المئات  من نسخ المكون.

2023-04-03 19:45 UTC, medaminefh commented
@boussadjra شكرا على المراجعه

2023-04-04 03:20 UTC, boussadjra approved these changes
شكرا جزيلا على المساهمة

2023-04-04 03:20 UTC, merged